### ISSUE TITLE
puppet/archive dependency break compatibility with camptocamp/archive

### ISSUE THREAD

**Issue by lzecca78** [voxpupuli/puppet-rundeck#263]
### Affected Puppet, Ruby, OS and module versions/distributions

- Puppet:  4.3.2
- Ruby:  ruby 2.1.8p440 (2015-12-16 revision 53160) [x86_64-linux]
- Distribution: ubuntu 14.04
- Module version: 3.1.0

### How to reproduce (e.g Puppet code you use)
just put both camptocamp/archive and voxpupuli/puppet-rundeck 3.1.0 and unfortunately due to the following dependency : 

https://github.com/voxpupuli/puppet-rundeck/blob/master/metadata.json#L61-L64

it breaks the fix of the puppet/archive module  that was released from 1.0.0 ( https://forge.puppet.com/puppet/archive/changelog). 

### What are you seeing
This is the output of execution of librarian-puppet : 

```sh
 librarian-puppet install --verbose
[Librarian] Ruby Version: 2.3.1
[Librarian] Ruby Platform: x86_64-linux-gnu
[Librarian] Rubygems Version: 2.5.1
[Librarian] Librarian Version: 0.6.3
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.2.3
[Librarian] Project: /home/luca/Work/provisioning/environments/production
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/bin/git
[Librarian] Git Version: 2.7.4
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Analyzing spec and lock:
[Librarian]   Removed:
[Librarian]   ExplicitRemoved:
[Librarian]   Added:
[Librarian]     puppet-archive
[Librarian]     puppet-rundeck
[Librarian]   NonMatchingAdded:
[Librarian]     puppet-archive
[Librarian]     puppet-rundeck
[Librarian]   Changed:
[Librarian]   DeepKeep:
[Librarian]     arioch-ulimit
[Librarian]     bashtoni-timezone
[Librarian]     bfraser-grafana
[Librarian]     camptocamp-archive
[Librarian]     dalen-puppetdbquery
[Librarian]     dhoppe-fail2ban
[Librarian]     dwerder-graphite
[Librarian]     dwerder-redis
[Librarian]     elasticsearch-elasticsearch
[Librarian]     elasticsearch-logstash
[Librarian]     example42-hosts
[Librarian]     example42-mysql
[Librarian]     fiddyspence-sysctl
[Librarian]     fsalum-newrelic
[Librarian]     garethr-docker
[Librarian]     jdowning-awscli
[Librarian]     lesaux-kibana4
[Librarian]     luxflux-openvpn
[Librarian]     maestrodev-android
[Librarian]     maestrodev-rvm
[Librarian]     petems-swap_file
[Librarian]     puppet-puppetboard
[Librarian]     puppetlabs-apt
[Librarian]     puppetlabs-git
[Librarian]     puppetlabs-nodejs
[Librarian]     puppetlabs-ntp
[Librarian]     puppetlabs-postgresql
[Librarian]     puppetlabs-puppetdb
[Librarian]     puppetlabs-rabbitmq
[Librarian]     puppetlabs-stdlib
[Librarian]     puppetlabs-tagmail
[Librarian]     puppetlabs-vcsrepo
[Librarian]     rmueller-cron
[Librarian]     saz-sudo
[Librarian]     sensu-sensu
[Librarian]     unibet-go
[Librarian]     yelp-uchiwa
[Librarian]   ShallowStrip:
[Librarian] Resolving puppet-archive (= 1.1.1) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module puppet-archive found versions: 1.1.1, 1.1.0, 1.0.0, 0.5.1, 0.5.0, 0.4.8, 0.4.4
[Librarian]     Checking puppet-archive/1.1.1 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved puppet-archive (= 1.1.1) <https://forgeapi.puppetlabs.com> at puppet-archive/1.1.1 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved puppet-archive (= 1.1.1) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving puppet-rundeck (= 3.1.0) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module puppet-rundeck found versions: 3.1.0, 3.0.0, 2.2.0, 2.1.0, 2.0.0, 1.2.0, 1.1.0
[Librarian]     Checking puppet-rundeck/3.1.0 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved puppet-rundeck (= 3.1.0) <https://forgeapi.puppetlabs.com> at puppet-rundeck/3.1.0 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved puppet-rundeck (= 3.1.0) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving pltraining-dirtree (>= 0) <(no source specified)>
[Librarian]   Checking manifests
[Librarian]   Module pltraining-dirtree found versions: 0.3.0, 0.2.2
[Librarian]     Checking pltraining-dirtree/0.3.0 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved pltraining-dirtree (>= 0) <(no source specified)> at pltraining-dirtree/0.3.0 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved pltraining-dirtree (>= 0) <(no source specified)>
[Librarian] Conflict between puppet-archive (< 1.0.0, >= 0.3.0) <https://forgeapi.puppetlabs.com> and puppet-archive/1.1.1 <https://forgeapi.puppetlabs.com>
Could not resolve the dependencies.
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/action/persist_resolution_mixin.rb:11:in `persist_resolution'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:32:in `run'
/var/lib/gems/2.3.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/action/resolve.rb:10:in `run'
/var/lib/gems/2.3.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:104:in `resolve!'
/var/lib/gems/2.3.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:68:in `install'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/var/lib/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
/var/lib/gems/2.3.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
/var/lib/gems/2.3.0/gems/librarian-puppet-2.2.3/bin/librarian-puppet:7:in `<top (required)>'
/usr/local/bin/librarian-puppet:23:in `load'
/usr/local/bin/librarian-puppet:23:in `<main>'
```

### What behaviour did you expect instead
Raise the puppet-archive dependency version to the last one because it allows puppet/archive and camptocamp/archive to live together without creating issues.

**Comment by bastelfreak** [comment]
Hi @lzecca78, thanks for opening the issue. Are you able to provide us a PR with the change?

**Comment by lzecca78** [comment]
Hi @bastelfreak , i would like to, but when i try to push the branch it gives to me a 403 http status.
Anyway, the fix is : 

```git 
diff --git a/metadata.json b/metadata.json
index 270729b..5c28152 100644
--- a/metadata.json
+++ b/metadata.json
@@ -60,7 +60,7 @@
     },
     {
       "name": "puppet/archive",
-      "version_requirement": ">= 0.3.0 <1.0.0"
+      "version_requirement": ">= 0.3.0 <=1.1.1"
     }
   ]
 }
```

**Comment by lzecca78** [comment]
Hi @bastelfreak, can you please enable me to push PR ?

**Comment by petems** [comment]
@lzecca78 Hi! You don't need to push PR to the original branch. You can fork the repository, push your branch to the fork, then open a pull-request to the original with the change: 

See https://help.github.com/articles/fork-a-repo/

**Comment by lzecca78** [comment]
@petems, thank you for the tip. I tried to send a PR with the change, but it breaks the tests in something that doesn't seem related with the change itself. 
Can you please give a look and let me know if i can help you to go ahead ?

**Comment by alexjfisher** [comment]
Fixed in https://github.com/voxpupuli/puppet-rundeck/pull/264
